#!/bin/bash

pip install numpy
pip install django
pip install nltk


if [ ! -d templates ]; then
	mkdir templates
fi

cp -f 1.html templates
cp -f 2-1.html templates
cp -f 2-2.html templates
cp -f 3-1.html templates
cp -f 3-2.html templates
cp -f 4-1.html templates
cp -f 4-2.html templates


$HOME/elasticsearch-7.6.2/bin/elasticsearch -d

flask run
